//Install vs code extension "REST CLIENT" for testing these api
// CRUD OPERATION ON USER

### ADD USER
POST http://localhost:4000/api/users/add
Content-Type: application/json

    {
    "name":"Tuyisenge",
    "email":"tuyi6@gmail.com",
    "password":"semytuyi"
    }



### USER LOGIN
POST http://localhost:4000/api/users/login
Content-Type: application/json

    {
    "email":"tuyisengesamy6@gmail.com",
    "password":"semytuyi"
    }

###GET ALL USERS
GET  http://localhost:4000/api/users/



### DELETE USER
DELETE http://localhost:4000/api/users/delete/62667dd11f5655dbbbf3401b



###GET ALL QUERY
// CRUD ON QUERY
GET  http://localhost:4000/query/



### GET A SINGLE QUERY
GET http://localhost:4000/query/6266193b899b63f894cedec7



### ADD A QUERY
POST http://localhost:4000/query/add/
Content-Type: application/json

    {
    "name":"Tuyisenge",
    "email":"tuyi6@gmail.com",
    "message":"Win or lose, at least your are doing something"
    }



###CREATE ARTICLE

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjRlZmQ4YzFiMDI3MzdhN2FjNjU0ZiIsImlhdCI6MTY1MDg3NzA0MSwiZXhwIjoxNjUzNDY5MDQxfQ.k_UTzDlZPnSx1v79HjSPyUbnJKDbQXHUxwgs8ya8kpc
POST http://localhost:4000/article/add/
Content-Type: application/json
Authorization: Bearer {{token}}

    {
    "title":"self awareness is important",
    "authorName":"Tuyisenge Samuel",
    "content":"you have to master your emotion in every situation"
    }



###
//get all articles
GET http://localhost:4000/article/



### get single article
GET http://localhost:4000/article/62669a079f1da88b1271943b




### update article
PATCH  http://localhost:4000/article/update/626696297884e14369fa5335
Content-Type: application/json
Authorization: Bearer {{token}}

    {
    "title":"UNIT TESTING",
    "authorName":"Tuyisenge Samuel",
    "content":"it is not going to be easy"
    }




### DELETE ARTICLE
DELETE  http://localhost:4000/article/delete/62669a079f1da88b1271943b
Content-Type: application/json
Authorization: Bearer {{token}}


### COMMENTING ON ARTICLE
POST  http://localhost:4000/article/comment/626696297884e14369fa5335
Content-Type: application/json
Authorization: Bearer {{token}}

    {
        "comment":"we never finish what?"
    }
